name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'compile', 'build:types']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ${{ matrix.step }}
      run: |
        yarn
        yarn ${{ matrix.step }}