name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'compile', 'build:types']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
      - name: Type definitions ${{ matrix.step }}
      - uses: actions/checkout@v1
        run: |
          cd pacakges/type-definitions
          yarn
          yarn ${{ matrix.step }}
      
      - name: Crust pin ${{ matrix.step }}
        uses: actions/checkout@v1
        run: |
          cd packages/crust-pin
          yarn
          yarn ${{ matrix.step }}

      